### ISSUE TITLE
[SUGGESTION] small icon for the Badges

### ISSUE THREAD

**Issue by Louis9902** [InventivetalentDev/badges.spiget.org#1]
Maybe something like the spigot icon, like the curse forge one from way2muchnoise 
[CurseForge Badges](http://cf.way2muchnoise.eu/)
![CurseForge Badges](http://cf.way2muchnoise.eu/just-enough-items-jei.svg)

**Comment by InventivetalentDev** [comment]
I don't think the library I'm using supports icons, I might have to look into another way at some point.
